name: CI with tox
on: [push]

jobs:
  api-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: PIP upgrade
      run: python -m pip install --upgrade pip
    - name: Install tox
      run: pip install tox
    - name: Install poetry
      run: pip install poetry
    - name: Run tests
      run: tox -e test

  py-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set Up Python
        uses: actions/setup-python@v1
      - name: PIP upgrade
        run: python -m pip install --upgrade pip
      - name: Install tox
        run: pip install tox
      - name: Run linter
        run: |
          tox -e lint

  js-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up NodeJS
        uses: actions/setup-node@v1
      - name: Install deps
        working-directory: frontend
        run: npm install
      - name: Run linter
        working-directory: frontend
        run: npm run lint
